import type { LeadRecord } from "../types";
export type BannerColumn = {
  key: string;
  label: string;
  labelClass: string;
  groupLabel?: string;
  groupClass?: string;
  minWidthClass?: string;
  minWidthPx?: number;
};

export const BANNER_GROUP_LIGHT_BG_CLASS: Record<string, string> = {
  STATUS: "bg-blue-200",
  ENQUIRY: "bg-pink-200",
  CUSTOMER: "bg-emerald-200",
  TRAVEL: "bg-purple-200",
  VEHICLE: "bg-blue-100",
  BAGGAGE: "bg-amber-200",
  TS_REPORT: "bg-rose-200",
  ACTION: "bg-lime-200",
  ITINERARY: "bg-cyan-200",
  PASSANGER: "bg-emerald-200",
  "Travel Req.": "bg-rose-200",
};

export const BANNER_GROUP_BG_CLASS: Record<string, string> = {
  STATUS: "bg-blue-950",
  ENQUIRY: "bg-pink-700",
  CUSTOMER: "bg-emerald-900",
  TRAVEL: "bg-purple-800",
  VEHICLE: "bg-blue-800",
  BAGGAGE: "bg-amber-800",
  TS_REPORT: "bg-rose-900",
  ACTION: "bg-lime-800",
  ITINERARY: "bg-cyan-800",
  PASSANGER: "bg-emerald-700",
  "Travel Req.": "bg-rose-800",
};

export const OCCASION_COLOR_MAP: Record<string, string> = {
  Wedding: "text-red-900 font-bold",
  Vacation: "text-orange-900 font-bold",
  Pilgrimage: "text-cyan-700 font-bold",
  Corporate: "text-pink-700 font-bold",
  Event: "text-blue-900 font-bold",
  Local: "text-green-900 font-bold",
};
export const SERVICE_TYPE_COLOR_MAP: Record<string, string> = {
  "Round Trip Drop": "text-green-600 font-bold",
};
export const statusClassMap: Record<LeadRecord["status"], string> = {
  New: "bg-blue-100 text-blue-600",
  KYC: "bg-amber-100 text-amber-600",
  RFQ: "bg-red-100 text-red-800",
  HOT: "bg-pink-100 text-pink-600",
  Book: "bg-green-600 text-white font-bold",
  "Veh-n": "bg-purple-100 text-purple-600",
  Lost: "bg-black text-white font-bold",
  Blank: "bg-gray-100 text-gray-600",
};

export const LEAD_STATUS_OPTIONS: LeadRecord["status"][] = [
  "New",
  "KYC",
  "RFQ",
  "HOT",
  "Book",
  "Veh-n",
  "Lost",
  "Blank",
];

export const TABLE_BANNER_COLUMNS: BannerColumn[] = [
  {
    key: "actions",
    label: "Full View",
    groupLabel: "ACTION",
    labelClass: "",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
  },
  {
    key: "status",
    label: "STATUS",
    groupLabel: "STATUS",
    groupClass: "text-white",
    labelClass: "text-white font-extrabold text-xl",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
  },
  {
    key: "aged",
    label: "AGED",
    groupLabel: "STATUS",
    groupClass: "text-white",
    labelClass: "text-white font-extrabold text-xl",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "liveorexpiry",
    label: "LIVE/EXPIRY",
    groupLabel: "STATUS",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "date",
    label: "DATE",
    groupLabel: "ENQUIRY",
    groupClass: "text-white",
    labelClass: "text-white font-black",
    minWidthClass: "min-w-[160px]",
    minWidthPx: 160,
  },
  {
    key: "source",
    label: "SOURCE",
    groupLabel: "ENQUIRY",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
  },
  {
    key: "presales_id",
    label: "PRESALES",
    groupLabel: "ENQUIRY",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
  },
  {
    key: "fullName",
    label: "FULL NAME",
    groupLabel: "CUSTOMER",
    groupClass: "text-white",
    labelClass: "text-white font-black",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "companyName",
    label: "COMPANY",
    groupLabel: "CUSTOMER",
    groupClass: "text-white",
    labelClass: "text-white font-black",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "customerCategoryType",
    label: "TYPE",
    groupLabel: "CUSTOMER",
    groupClass: "text-white",
    labelClass: "text-white font-black",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
  },
  {
    key: "customerType",
    label: "Category",
    groupLabel: "CUSTOMER",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[120px]",
    minWidthPx: 120,
  },
  {
    key: "pickupDateTime",
    label: "PICKUP DATE",
    groupLabel: "TRAVEL",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[140px]",
    minWidthPx: 140,
  },
  {
    key: "dropDateTime",
    label: "DROP DATE",
    groupLabel: "TRAVEL",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[140px]",
    minWidthPx: 140,
  },
  {
    key: "days",
    label: "DAYS",
    groupLabel: "TRAVEL",
    groupClass: "text-white",
    labelClass: "text-white font-black",
    minWidthClass: "min-w-[60px]",
    minWidthPx: 60,
  },
  {
    key: "pickupcity",
    label: "PICKUP CITY",
    groupLabel: "ITINERARY",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "pickupAddress",
    label: "PICKUP ADDRESS",
    groupLabel: "ITINERARY",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "itinerary",
    label: "ITINERARY",
    groupLabel: "ITINERARY",
    groupClass: "text-white",
    labelClass: "text-white font-extrabold text-xl",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
  },
  {
    key: "dropcity",
    label: "DROP CITY",
    groupLabel: "ITINERARY",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "dropAddress",
    label: "DROP ADDRESS",
    groupLabel: "ITINERARY",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "km",
    label: "KM",
    groupLabel: "ITINERARY",
    groupClass: "text-white",
    labelClass: "text-white font-bold",
    minWidthClass: "min-w-[60px]",
    minWidthPx: 60,
  },
  {
    key: "occasion",
    label: "OCCASION",
    groupLabel: "Travel Req.",
    groupClass: "text-white",
    labelClass: "text-white font-bold",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
  },
  {
    key: "serviceType",
    label: "SERVICE",
    groupLabel: "Travel Req.",
    groupClass: "text-white",
    labelClass: "text-white font-bold",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
  },
  {
    key: "tripType",
    label: "TRIP TYPE",
    groupLabel: "Travel Req.",
    groupClass: "text-white",
    labelClass: "text-white font-bold",
    minWidthClass: "min-w-[100px]",
    minWidthPx: 100,
  },
  {
    key: "passengerTotal",
    label: "PAX",
    groupLabel: "PASSANGER",
    groupClass: "text-white",
    labelClass: "text-white font-black",
    minWidthClass: "min-w-[60px]",
    minWidthPx: 60,
  },
  {
    key: "petsNumber",
    label: "PETS",
    groupLabel: "PASSANGER",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[60px]",
    minWidthPx: 60,
  },
  {
    key: "totalBaggage",
    label: "BAGGAGE",
    groupLabel: "PASSANGER",
    groupClass: "text-white",
    labelClass: "text-white font-black",
    minWidthClass: "min-w-[60px]",
    minWidthPx: 60,
  },
  {
    key: "vehicles",
    label: "Veh. 1",
    groupLabel: "VEHICLE",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "vehicle2",
    label: "Veh. 2",
    groupLabel: "VEHICLE",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[80px]",
    minWidthPx: 80,
  },
  {
    key: "vehicle3",
    label: "Veh. 3",
    groupLabel: "VEHICLE",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[80px]",
    minWidthPx: 80,
  },
  {
    key: "requirementVehicle",
    label: "Veh. Req ",
    groupLabel: "VEHICLE",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[80px]",
    minWidthPx: 80,
  },
  {
    key: "remarks",
    label: "Special Req. of Customer",
    groupLabel: "TS_REPORT",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "lost_reason",
    label: "LOST REASON",
    groupLabel: "TS_REPORT",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "lostReasonDetails",
    label: "Lost Reason Details",
    groupLabel: "TS_REPORT",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
  {
    key: "followUp",
    label: "Follow Up",
    groupLabel: "TS_REPORT",
    groupClass: "text-white",
    labelClass: "text-white font-semibold",
    minWidthClass: "min-w-[150px]",
    minWidthPx: 150,
  },
];
export const MONTH_OPTIONS = [
  { value: "04", label: "Apr" },
  { value: "05", label: "May" },
  { value: "06", label: "Jun" },
  { value: "07", label: "Jul" },
  { value: "08", label: "Aug" },
  { value: "09", label: "Sep" },
  { value: "10", label: "Oct" },
  { value: "11", label: "Nov" },
  { value: "12", label: "Dec" },
  { value: "01", label: "Jan" },
  { value: "02", label: "Feb" },
  { value: "03", label: "Mar" },
];
export const CITY_OPTIONS = [
  "Delhi",
  "Mumbai",
  "Chandigarh",
  "Varanasi",
  "Prayagraj",
] as const;

export const LEAD_CUSTOMER_TYPES: LeadRecord["customerType"][] = [
  "Personal",
  "Corporate",
  "Travel Agent",
];
export const LEAD_SERVICE_TYPES: LeadRecord["serviceType"][] = [
  "Wedding",
  "Vacation",
  "Pilgrimage",
  "Corporate",
  "Local",
];
export const LEAD_TRIP_TYPES: LeadRecord["tripType"][] = [
  "pickup",
  "drop",
  "both",
];
